---
name: Tabletop Simulator

on:
    push:
        branches: [main, beta, ni]
    pull_request:
        branches: [main, beta, ni]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install "tabletop-tools~=0.7.1"
            - name: Build mod
              run: |
                  tts repack
            - uses: actions/upload-artifact@v2
              with:
                  name: spirit-island-ci
                  path: build/packed-savegame.json
                  if-no-files-found: error
            - name: Format mod
              run: |
                  tts fmt
                  git diff --exit-code
